### PR TITLE
Complete notebooks

### PR DESCRIPTION
**Pull request by melissawm**
@cooperrc I did a full pass at the notebooks to make them consistent, organized and flowing in the text and examples. I left a couple of placeholders for self-assessments and moved a few things around to make the contents more balanced - the first two notebooks were too long. 

This looks reasonable to me now, but I'd really appreciate if you could take a look. Also feel free to point to any typos or things that don't make sense. 

As soon as we agree on the structure I can change the course description to better reflect this outline.

Cheers!

### CODE REVIEW

**Comment by cooperrc** [comment]
Thanks @melissawm !!

I'll take a look today and review tomorrow (10/11 + 10/12).

**Review by cooperrc — COMMENTED** [review]
I prefer "process" to "manipulate" data. Im adding them in a follow-up commit

**Review by cooperrc — COMMENTED** [review]
It might also help to define a `cities` array with the city names that you can use in `01_Intro` and describe strings

**Review by cooperrc — COMMENTED** [review]
I love the views+copies & advanced indexing, but they dont directly contribute to processing the data. Maybe we could change the application to rescale the data in a new array, sliced array and show how we need to `copy` the sliced array. e.g. only look at top 10 cost of living cities, and rescale to San Francisco.

**Comment by melissawm** [comment]
> I love the views+copies & advanced indexing, but they dont directly contribute to processing the data. Maybe we could change the application to rescale the data in a new array, sliced array and show how we need to `copy` the sliced array. e.g. only look at top 10 cost of living cities, and rescale to San Francisco.

Good point, I'll try to think about that later today!

**Comment by melissawm** [comment]
I am merging this so it's easier to keep working but I have captured your suggestion in #5

**Pull request merged**
